services:
  nestjs-app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.${NODE_ENV:-development}
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    volumes:
      - ./:/app
    depends_on:
      - postgres
      - redis
      - rabbitmq
    command: >
      sh -c "if [ \"$${NODE_ENV}\" = 'production' ]; then
                node dist/main;
             else
                npx nest start --watch;
             fi"

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672" # Management UI

volumes:
  pgdata:
